- hosts: localhost
  gather_facts: no

  tasks:
    - debug:
        msg: >- 
          cron: 
            name: "On server {{ item.0.username }} with username {{ item.0.sshkey }}"
            binary: "{{ item.1.binary }}"
            command: "{{ item.1.command }}"
      loop: "{{ none_secure_users | subelements('process') }}"
      loop_control:
        label: "{{ item.0.username }}"
      vars:
        none_secure_users:
          - username: srv-test-1
            home: /var/ftp/srv-test-1
            sshkey: mykey1
            process:
              - binary: "*/15 * * * *"
                command: "curl example.com"
              - binary: "*/30 * * * *"
                command: "curl 30.example.com"

          - username: srv-test-2
            home: /var/ftp/srv-test-2
            sshkey: mykey2
            process:
              - binary: "*/20 * * * *"
                command: "curl example.com"
